### ISSUE TITLE
Support for meshgrid 

### ISSUE THREAD

**Issue by elyurn** [groscot/jupythree#1]
Hello,

Well done for you great work with this module. Do you plan to propose support for direct computation of (N,N,N) dimensions numpy array meshgrid ? Thank you!

**Comment by groscot** [comment]
Hey, I have some code to draw lines too and was planning to release it later if needed :) Tho I've worked a lot with (N,N,N,3) meshgrids and displaying the full grid makes it hardly visible. What I do in general is reshape the array to (-1,3) and display it like a normal pointcloud. Or sometimes, I draw only the outer edges and that's more legible.
I'll try to share this soon!
